create database testdb;
use testdb;
INSERT INTO `user_info` (user_info.`id`,user_info.`name`,user_info.`password`,user_info.`salt`,user_info.`username`) VALUES (1, '管理员','951cd60dec2104024949d2e0b2af45ae', 'xbNIxrQfn6COSYn1/GdloA==', 'wmyskxz');
INSERT INTO `sys_permission` (sys_permission.`id`,sys_permission.`description`,sys_permission.`name`,sys_permission.`url`) VALUES (1,'查询用户','userInfo:view','/userList');
INSERT INTO `sys_permission` (sys_permission.`id`,sys_permission.`description`,sys_permission.`name`,sys_permission.`url`) VALUES (2,'增加用户','userInfo:add','/userAdd');
INSERT INTO `sys_permission` (sys_permission.`id`,sys_permission.`description`,sys_permission.`name`,sys_permission.`url`) VALUES (3,'删除用户','userInfo:delete','/userDelete');
INSERT INTO `sys_role` (sys_role.`id`,sys_role.`description`,sys_role.`name`) VALUES (1,'管理员','admin');
INSERT INTO `sys_role_permission` (sys_role_permission.`permission_id`,sys_role_permission.`role_id`) VALUES (1,1);
INSERT INTO `sys_role_permission` (sys_role_permission.`permission_id`,sys_role_permission.`role_id`) VALUES (2,1);
INSERT INTO `sys_user_role` (sys_user_role.`role_id`,sys_user_role.`uid`) VALUES (1,1);
